# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
        exclude: ^demo_app_requirements/
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
        exclude: ^demo_app_requirements/
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        verbose: true
        args: [ --ignore-missing-imports]
        additional_dependencies: [types-requests]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black"]
  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.1
    hooks:
      - id: auto-walrus
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=perflint", # Load an extension
            "--ignore=./tests"
          ]
