name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: Black
        run: |
          pip install black
          black . --check
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: Flake8
        run: |
          pip install flake8 flake8-docstrings
          flake8 .
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: Mypy
        run: |
          pip install -r tests/requirements.txt
          pip install mypy
          pip install types-requests
          mypy src
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-python@v2
          with:
            python-version: '3.11'
        - uses: actions/checkout@v2
        - name: Pytest 3.11
          run: |
            pip install -r requirements.txt
            pytest .